"""Create evidence board tables and add structured logging

Revision ID: f3ab58d02680
Revises: fb9a2be84179
Create Date: 2025-09-06 15:27:23.396033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ab58d02680'
down_revision: Union[str, Sequence[str], None] = 'fb9a2be84179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('extracted_idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=False),
    sa.Column('pain_point', sa.Text(), nullable=False),
    sa.Column('solution_idea', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('business_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_post_id'], ['source_post.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_log', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('task_log', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_log', 'data')
    op.drop_column('task_log', 'type')
    op.drop_table('extracted_idea')
    op.drop_table('source_post')
    # ### end Alembic commands ###
